CREATE TABLE links (
  id BIGINT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  url VARCHAR(255) NOT NULL,
  title VARCHAR(255) NOT NULL,
  trip_id UUID,
  FOREIGN KEY (trip_id) REFERENCES trips(id) ON DELETE CASCADE
);